image: ruby:2.5.1-slim-stretch

variables:
  JEKYLL_ENV: production

pages:
  stage: deploy
  script:
  - apt-get update
  - apt-get install build-essential ruby-dev libstdc++6
  - bundle install
  - jekyll build -d public/
  artifacts:
    paths:
    - public
  only:
  - master
