image: jekyll/jekyll:minimal

variables:
  JEKYLL_ENV: production

pages:
  stage: deploy
  script:
  - bundle install
  - jekyll build -d public/
  artifacts:
    paths:
    - public
  only:
  - master
