# Theme settings
doks:
    baseurl: /docs
    color_theme: blue # Available themes: blue (default), green, purple, red and yellow
    header:
        logo:
            text: 
            image: true
        nav:
            - item_name: Home
              item_url:  /
            - item_name: Release Notes
              item_url: /release_notes
            - item_name: Contact
              item_url: /contact
    footer:
        content:
            logo:
                text: Rio/OS
                image:
            copyright: Copyright &copy; 2018. - Rio Advancement Inc <br>All rights reserved.
        social_list:
            - network_name: facebook
              profile_url: 'https://www.facebook.com/Riocorpinc'
            - network_name: linkedin
              profile_url: 'https://www.linkedin.com/company/rio-advancement'
            - network_name: github
              profile_url: 'https://github.com/rioadvancement#'
    google_analytics:
        tracking_code: # Add your Google Analytics tracking code to activate Google Analytics
    comments:
        disqus_forum_shortname: # Add your disqus forum shortname to activate comments
    swagger:
        json: 'https://app.swaggerhub.com/apiproxy/schema/file/riocorp/rioos/2.0/swagger.json?pretty=true'    
# Gems
plugins: []

# SASS settings
sass:
    sass_dir: ./doks-theme/_sass
    style: :compressed

# Jekyll settings
layouts_dir: ./doks-theme/_layouts
includes_dir: ./doks-theme/_includes
exclude: [ 'README.md', 'CHANGELOG.md' ]
permalink: /:title/
